accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'accounts'


urlpatterns = [
    path('signup', views.signup ,name='signup'),
    path('profile', views.Profile ,name='profile'),
    path('profile/edit', views.profileedit ,name='profile_edit'),


]

job/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'job'



urlpatterns = [
    path('', views.job_list , name='job_list'),
    path('add', views.add_job, name='add_job'),
    path('<str:slug>', views.job_details , name='job_detail'),
]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from job import urls
from accounts import urls
from contact import urls
from django.conf import settings
from django.conf.urls.static import static 



urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls'),name='accounts'),
    path('jobs/', include('job.urls',namespace='jobs')),
    path('admin/', admin.site.urls), 
    path('contactus/', include('contact.urls',namespace='contactus')),
]




urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.


class profile(models.Model):
    user    =   models.OneToOneField(User, on_delete=models.CASCADE)
    city    =   models.ForeignKey('City',on_delete=models.CASCADE,null=True,blank=True)
    phone   =   models.CharField(max_length=15)
    image   =   models.ImageField(upload_to='profile_pic/')

    def __str__(self):
        return str(self.user)
    


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile.objects.create(user=instance)




class City(models.Model):
    name = models.CharField(max_length=120)
    def __str__(self):
        return str(self.name)
    

 

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import profile



class signuo_FORM(UserCreationForm):
    class Meta:
        model   =   User
        fields  =   ['username','email','password1','password2']

class UserForm(forms.ModelForm):
    class Meta:
        model  = User
        fields =    ['username','first_name','last_name','email']

class ProfileForm(forms.ModelForm):
    class Meta:
        model  = profile
        fields = ['city','phone','image']

accounts/views.py
from django.shortcuts import render , redirect , reverse
from .forms import signuo_FORM , UserForm , ProfileForm
from django.contrib.auth import authenticate , login
from .models import profile 

# Create your views here.



def signup(request):
    if request.method == "POST":
        form = signuo_FORM(request.POST)
        if form.is_valid:
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username,password=password)
            login(request,user)
            return redirect('/accounts/profile')
    else:
        form = signuo_FORM()

    return render(request,'registration/signup.html',{'form' : form})


def Profile(request):
    profilo = profile.objects.get(user=request.user)

    return render(request,'accounts/profile.html',{'profile' : profilo})

def profileedit(request):
    profilo = profile.objects.get(user=request.user)
    if request.method == "POST":
            userform = UserForm(request.POST,instance=request.user)
            ProfileForm2 = ProfileForm(request.POST,request.FILES,instance=profilo)
            if userform.is_valid and ProfileForm2.is_valid():
                userform.save()
                my_pro = ProfileForm2.save(commit=False)
                my_pro.user = request.user
                my_pro.save()
                return redirect(reverse('accounts:profile'))
    else :
            userform = UserForm(instance=request.user)
            ProfileForm2 = ProfileForm(instance=profilo)
    return render(request,'accounts/profile_edit.html',{'userform' : userform , 'ProfileForm2' : ProfileForm2})

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job.title}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Profile Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Name : <span>{{profile}}</span></li>
                                <li>address : <span>{{profile.city}}</span></li>
                                <li>Phone : <span>{{profile.phone}}</span></li>
                                <li>Email : <span>{{profile.user.email}}</span></li>
                                <div class = "p-5">
                                    <a class="boxed-btn3 w-100" href="{% url 'accounts:profile_edit' %}">Edit</a>
                                </div>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-xl-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        <h4>Edit profile</h4>
                        <form  method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form userform %}
                            {% bootstrap_form ProfileForm2 %}
                            {% buttons %}
                                <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
                            {% endbuttons %}

                        </form>

                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>


{% endblock body %}